//! Default mihomo configuration generation.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};

/// Ensure a minimal mihomo `config.yaml` exists in the given directory.
///
/// If one already exists, this is a no-op. Returns `true` when a new config
/// was written.
pub fn ensure_default_config(config_dir: &Path) -> Result<bool> {
    let config_path = config_dir.join("config.yaml");
    if config_path.exists() {
        return Ok(false);
    }

    fs::create_dir_all(config_dir)
        .with_context(|| format!("cannot create {}", config_dir.display()))?;

    let default_config = r#"# mihomo default config (auto-generated by mihomo-tui)
mixed-port: 7890
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: info
unified-delay: true
tcp-concurrent: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query

proxies: []

proxy-groups: []

rules:
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT
"#;

    fs::write(&config_path, default_config)
        .with_context(|| format!("cannot write {}", config_path.display()))?;
    Ok(true)
}
